/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.service;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

public class AppTest {
    @Test
    public void testApp() {
        assertEquals(1, 1, "1 should equal 1");
    }
}
